namespace Common.Drawing
{
    public sealed class Brushes
    {
        public static Brush Transparent { get { return System.Drawing.Brushes.Transparent; } }
        public static Brush AliceBlue { get { return System.Drawing.Brushes.AliceBlue; } }
        public static Brush AntiqueWhite { get { return System.Drawing.Brushes.AntiqueWhite; } }
        public static Brush Aqua { get { return System.Drawing.Brushes.Aqua; } }
        public static Brush Aquamarine { get { return System.Drawing.Brushes.Aquamarine; } }
        public static Brush Azure { get { return System.Drawing.Brushes.Azure; } }
        public static Brush Beige { get { return System.Drawing.Brushes.Beige; } }
        public static Brush Bisque { get { return System.Drawing.Brushes.Bisque; } }
        public static Brush Black { get { return System.Drawing.Brushes.Black; } }
        public static Brush BlanchedAlmond { get { return System.Drawing.Brushes.BlanchedAlmond; } }
        public static Brush Blue { get { return System.Drawing.Brushes.Blue; } }
        public static Brush BlueViolet { get { return System.Drawing.Brushes.BlueViolet; } }
        public static Brush Brown { get { return System.Drawing.Brushes.Brown; } }
        public static Brush BurlyWood { get { return System.Drawing.Brushes.BurlyWood; } }
        public static Brush CadetBlue { get { return System.Drawing.Brushes.CadetBlue; } }
        public static Brush Chartreuse { get { return System.Drawing.Brushes.Chartreuse; } }
        public static Brush Chocolate { get { return System.Drawing.Brushes.Chocolate; } }
        public static Brush Coral { get { return System.Drawing.Brushes.Coral; } }
        public static Brush CornflowerBlue { get { return System.Drawing.Brushes.CornflowerBlue; } }
        public static Brush Cornsilk { get { return System.Drawing.Brushes.Cornsilk; } }
        public static Brush Crimson { get { return System.Drawing.Brushes.Crimson; } }
        public static Brush Cyan { get { return System.Drawing.Brushes.Cyan; } }
        public static Brush DarkBlue { get { return System.Drawing.Brushes.DarkBlue; } }
        public static Brush DarkCyan { get { return System.Drawing.Brushes.DarkCyan; } }
        public static Brush DarkGoldenrod { get { return System.Drawing.Brushes.DarkGoldenrod; } }
        public static Brush DarkGray { get { return System.Drawing.Brushes.DarkGray; } }
        public static Brush DarkGreen { get { return System.Drawing.Brushes.DarkGreen; } }
        public static Brush DarkKhaki { get { return System.Drawing.Brushes.DarkKhaki; } }
        public static Brush DarkMagenta { get { return System.Drawing.Brushes.DarkMagenta; } }
        public static Brush DarkOliveGreen { get { return System.Drawing.Brushes.DarkOliveGreen; } }
        public static Brush DarkOrange { get { return System.Drawing.Brushes.DarkOrange; } }
        public static Brush DarkOrchid { get { return System.Drawing.Brushes.DarkOrchid; } }
        public static Brush DarkRed { get { return System.Drawing.Brushes.DarkRed; } }
        public static Brush DarkSalmon { get { return System.Drawing.Brushes.DarkSalmon; } }
        public static Brush DarkSeaGreen { get { return System.Drawing.Brushes.DarkSeaGreen; } }
        public static Brush DarkSlateBlue { get { return System.Drawing.Brushes.DarkSlateBlue; } }
        public static Brush DarkSlateGray { get { return System.Drawing.Brushes.DarkSlateGray; } }
        public static Brush DarkTurquoise { get { return System.Drawing.Brushes.DarkTurquoise; } }
        public static Brush DarkViolet { get { return System.Drawing.Brushes.DarkViolet; } }
        public static Brush DeepPink { get { return System.Drawing.Brushes.DeepPink; } }
        public static Brush DeepSkyBlue { get { return System.Drawing.Brushes.DeepSkyBlue; } }
        public static Brush DimGray { get { return System.Drawing.Brushes.DimGray; } }
        public static Brush DodgerBlue { get { return System.Drawing.Brushes.DodgerBlue; } }
        public static Brush Firebrick { get { return System.Drawing.Brushes.Firebrick; } }
        public static Brush FloralWhite { get { return System.Drawing.Brushes.FloralWhite; } }
        public static Brush ForestGreen { get { return System.Drawing.Brushes.ForestGreen; } }
        public static Brush Fuchsia { get { return System.Drawing.Brushes.Fuchsia; } }
        public static Brush Gainsboro { get { return System.Drawing.Brushes.Gainsboro; } }
        public static Brush GhostWhite { get { return System.Drawing.Brushes.GhostWhite; } }
        public static Brush Gold { get { return System.Drawing.Brushes.Gold; } }
        public static Brush Goldenrod { get { return System.Drawing.Brushes.Goldenrod; } }
        public static Brush Gray { get { return System.Drawing.Brushes.Gray; } }
        public static Brush Green { get { return System.Drawing.Brushes.Green; } }
        public static Brush GreenYellow { get { return System.Drawing.Brushes.GreenYellow; } }
        public static Brush Honeydew { get { return System.Drawing.Brushes.Honeydew; } }
        public static Brush HotPink { get { return System.Drawing.Brushes.HotPink; } }
        public static Brush IndianRed { get { return System.Drawing.Brushes.IndianRed; } }
        public static Brush Indigo { get { return System.Drawing.Brushes.Indigo; } }
        public static Brush Ivory { get { return System.Drawing.Brushes.Ivory; } }
        public static Brush Khaki { get { return System.Drawing.Brushes.Khaki; } }
        public static Brush Lavender { get { return System.Drawing.Brushes.Lavender; } }
        public static Brush LavenderBlush { get { return System.Drawing.Brushes.LavenderBlush; } }
        public static Brush LawnGreen { get { return System.Drawing.Brushes.LawnGreen; } }
        public static Brush LemonChiffon { get { return System.Drawing.Brushes.LemonChiffon; } }
        public static Brush LightBlue { get { return System.Drawing.Brushes.LightBlue; } }
        public static Brush LightCoral { get { return System.Drawing.Brushes.LightCoral; } }
        public static Brush LightCyan { get { return System.Drawing.Brushes.LightCyan; } }
        public static Brush LightGoldenrodYellow { get { return System.Drawing.Brushes.LightGoldenrodYellow; } }
        public static Brush LightGreen { get { return System.Drawing.Brushes.LightGreen; } }
        public static Brush LightGray { get { return System.Drawing.Brushes.LightGray; } }
        public static Brush LightPink { get { return System.Drawing.Brushes.LightPink; } }
        public static Brush LightSalmon { get { return System.Drawing.Brushes.LightSalmon; } }
        public static Brush LightSeaGreen { get { return System.Drawing.Brushes.LightSeaGreen; } }
        public static Brush LightSkyBlue { get { return System.Drawing.Brushes.LightSkyBlue; } }
        public static Brush LightSlateGray { get { return System.Drawing.Brushes.LightSlateGray; } }
        public static Brush LightSteelBlue { get { return System.Drawing.Brushes.LightSteelBlue; } }
        public static Brush LightYellow { get { return System.Drawing.Brushes.LightYellow; } }
        public static Brush Lime { get { return System.Drawing.Brushes.Lime; } }
        public static Brush LimeGreen { get { return System.Drawing.Brushes.LimeGreen; } }
        public static Brush Linen { get { return System.Drawing.Brushes.Linen; } }
        public static Brush Magenta { get { return System.Drawing.Brushes.Magenta; } }
        public static Brush Maroon { get { return System.Drawing.Brushes.Maroon; } }
        public static Brush MediumAquamarine { get { return System.Drawing.Brushes.MediumAquamarine; } }
        public static Brush MediumBlue { get { return System.Drawing.Brushes.MediumBlue; } }
        public static Brush MediumOrchid { get { return System.Drawing.Brushes.MediumOrchid; } }
        public static Brush MediumPurple { get { return System.Drawing.Brushes.MediumPurple; } }
        public static Brush MediumSeaGreen { get { return System.Drawing.Brushes.MediumSeaGreen; } }
        public static Brush MediumSlateBlue { get { return System.Drawing.Brushes.MediumSlateBlue; } }
        public static Brush MediumSpringGreen { get { return System.Drawing.Brushes.MediumSpringGreen; } }
        public static Brush MediumTurquoise { get { return System.Drawing.Brushes.MediumTurquoise; } }
        public static Brush MediumVioletRed { get { return System.Drawing.Brushes.MediumVioletRed; } }
        public static Brush MidnightBlue { get { return System.Drawing.Brushes.MidnightBlue; } }
        public static Brush MintCream { get { return System.Drawing.Brushes.MintCream; } }
        public static Brush MistyRose { get { return System.Drawing.Brushes.MistyRose; } }
        public static Brush Moccasin { get { return System.Drawing.Brushes.Moccasin; } }
        public static Brush NavajoWhite { get { return System.Drawing.Brushes.NavajoWhite; } }
        public static Brush Navy { get { return System.Drawing.Brushes.Navy; } }
        public static Brush OldLace { get { return System.Drawing.Brushes.OldLace; } }
        public static Brush Olive { get { return System.Drawing.Brushes.Olive; } }
        public static Brush OliveDrab { get { return System.Drawing.Brushes.OliveDrab; } }
        public static Brush Orange { get { return System.Drawing.Brushes.Orange; } }
        public static Brush OrangeRed { get { return System.Drawing.Brushes.OrangeRed; } }
        public static Brush Orchid { get { return System.Drawing.Brushes.Orchid; } }
        public static Brush PaleGoldenrod { get { return System.Drawing.Brushes.PaleGoldenrod; } }
        public static Brush PaleGreen { get { return System.Drawing.Brushes.PaleGreen; } }
        public static Brush PaleTurquoise { get { return System.Drawing.Brushes.PaleTurquoise; } }
        public static Brush PaleVioletRed { get { return System.Drawing.Brushes.PaleVioletRed; } }
        public static Brush PapayaWhip { get { return System.Drawing.Brushes.PapayaWhip; } }
        public static Brush PeachPuff { get { return System.Drawing.Brushes.PeachPuff; } }
        public static Brush Peru { get { return System.Drawing.Brushes.Peru; } }
        public static Brush Pink { get { return System.Drawing.Brushes.Pink; } }
        public static Brush Plum { get { return System.Drawing.Brushes.Plum; } }
        public static Brush PowderBlue { get { return System.Drawing.Brushes.PowderBlue; } }
        public static Brush Purple { get { return System.Drawing.Brushes.Purple; } }
        public static Brush Red { get { return System.Drawing.Brushes.Red; } }
        public static Brush RosyBrown { get { return System.Drawing.Brushes.RosyBrown; } }
        public static Brush RoyalBlue { get { return System.Drawing.Brushes.RoyalBlue; } }
        public static Brush SaddleBrown { get { return System.Drawing.Brushes.SaddleBrown; } }
        public static Brush Salmon { get { return System.Drawing.Brushes.Salmon; } }
        public static Brush SandyBrown { get { return System.Drawing.Brushes.SandyBrown; } }
        public static Brush SeaGreen { get { return System.Drawing.Brushes.SeaGreen; } }
        public static Brush SeaShell { get { return System.Drawing.Brushes.SeaShell; } }
        public static Brush Sienna { get { return System.Drawing.Brushes.Sienna; } }
        public static Brush Silver { get { return System.Drawing.Brushes.Silver; } }
        public static Brush SkyBlue { get { return System.Drawing.Brushes.SkyBlue; } }
        public static Brush SlateBlue { get { return System.Drawing.Brushes.SlateBlue; } }
        public static Brush SlateGray { get { return System.Drawing.Brushes.SlateGray; } }
        public static Brush Snow { get { return System.Drawing.Brushes.Snow; } }
        public static Brush SpringGreen { get { return System.Drawing.Brushes.SpringGreen; } }
        public static Brush SteelBlue { get { return System.Drawing.Brushes.SteelBlue; } }
        public static Brush Tan { get { return System.Drawing.Brushes.Tan; } }
        public static Brush Teal { get { return System.Drawing.Brushes.Teal; } }
        public static Brush Thistle { get { return System.Drawing.Brushes.Thistle; } }
        public static Brush Tomato { get { return System.Drawing.Brushes.Tomato; } }
        public static Brush Turquoise { get { return System.Drawing.Brushes.Turquoise; } }
        public static Brush Violet { get { return System.Drawing.Brushes.Violet; } }
        public static Brush Wheat { get { return System.Drawing.Brushes.Wheat; } }
        public static Brush White { get { return System.Drawing.Brushes.White; } }
        public static Brush WhiteSmoke { get { return System.Drawing.Brushes.WhiteSmoke; } }
        public static Brush Yellow { get { return System.Drawing.Brushes.Yellow; } }
        public static Brush YellowGreen { get { return System.Drawing.Brushes.YellowGreen; } }
        private Brushes(){}
    }
}
