
namespace Common.Drawing
{
    /// <summary>Pens for all the standard colors. This class cannot be inherited.</summary>
    /// <filterpriority>1</filterpriority>
    public sealed class Pens
    {
        public static Pen Transparent { get { return System.Drawing.Pens.Transparent; } }
        public static Pen AliceBlue { get { return System.Drawing.Pens.AliceBlue; } }
        public static Pen AntiqueWhite { get { return System.Drawing.Pens.AntiqueWhite; } }
        public static Pen Aqua { get { return System.Drawing.Pens.Aqua; } }
        public static Pen Aquamarine { get { return System.Drawing.Pens.Aquamarine; } }
        public static Pen Azure { get { return System.Drawing.Pens.Azure; } }
        public static Pen Beige { get { return System.Drawing.Pens.Beige; } }
        public static Pen Bisque { get { return System.Drawing.Pens.Bisque; } }
        public static Pen Black { get { return System.Drawing.Pens.Black; } }
        public static Pen BlanchedAlmond { get { return System.Drawing.Pens.BlanchedAlmond; } }
        public static Pen Blue { get { return System.Drawing.Pens.Blue; } }
        public static Pen BlueViolet { get { return System.Drawing.Pens.BlueViolet; } }
        public static Pen Brown { get { return System.Drawing.Pens.Brown; } }
        public static Pen BurlyWood { get { return System.Drawing.Pens.BurlyWood; } }
        public static Pen CadetBlue { get { return System.Drawing.Pens.CadetBlue; } }
        public static Pen Chartreuse { get { return System.Drawing.Pens.Chartreuse; } }
        public static Pen Chocolate { get { return System.Drawing.Pens.Chocolate; } }
        public static Pen Coral { get { return System.Drawing.Pens.Coral; } }
        public static Pen CornflowerBlue { get { return System.Drawing.Pens.CornflowerBlue; } }
        public static Pen Cornsilk { get { return System.Drawing.Pens.Cornsilk; } }
        public static Pen Crimson { get { return System.Drawing.Pens.Crimson; } }
        public static Pen Cyan { get { return System.Drawing.Pens.Cyan; } }
        public static Pen DarkBlue { get { return System.Drawing.Pens.DarkBlue; } }
        public static Pen DarkCyan { get { return System.Drawing.Pens.DarkCyan; } }
        public static Pen DarkGoldenrod { get { return System.Drawing.Pens.DarkGoldenrod; } }
        public static Pen DarkGray { get { return System.Drawing.Pens.DarkGray; } }
        public static Pen DarkGreen { get { return System.Drawing.Pens.DarkGreen; } }
        public static Pen DarkKhaki { get { return System.Drawing.Pens.DarkKhaki; } }
        public static Pen DarkMagenta { get { return System.Drawing.Pens.DarkMagenta; } }
        public static Pen DarkOliveGreen { get { return System.Drawing.Pens.DarkOliveGreen; } }
        public static Pen DarkOrange { get { return System.Drawing.Pens.DarkOrange; } }
        public static Pen DarkOrchid { get { return System.Drawing.Pens.DarkOrchid; } }
        public static Pen DarkRed { get { return System.Drawing.Pens.DarkRed; } }
        public static Pen DarkSalmon { get { return System.Drawing.Pens.DarkSalmon; } }
        public static Pen DarkSeaGreen { get { return System.Drawing.Pens.DarkSeaGreen; } }
        public static Pen DarkSlateBlue { get { return System.Drawing.Pens.DarkSlateBlue; } }
        public static Pen DarkSlateGray { get { return System.Drawing.Pens.DarkSlateGray; } }
        public static Pen DarkTurquoise { get { return System.Drawing.Pens.DarkTurquoise; } }
        public static Pen DarkViolet { get { return System.Drawing.Pens.DarkViolet; } }
        public static Pen DeepPink { get { return System.Drawing.Pens.DeepPink; } }
        public static Pen DeepSkyBlue { get { return System.Drawing.Pens.DeepSkyBlue; } }
        public static Pen DimGray { get { return System.Drawing.Pens.DimGray; } }
        public static Pen DodgerBlue { get { return System.Drawing.Pens.DodgerBlue; } }
        public static Pen Firebrick { get { return System.Drawing.Pens.Firebrick; } }
        public static Pen FloralWhite { get { return System.Drawing.Pens.FloralWhite; } }
        public static Pen ForestGreen { get { return System.Drawing.Pens.ForestGreen; } }
        public static Pen Fuchsia { get { return System.Drawing.Pens.Fuchsia; } }
        public static Pen Gainsboro { get { return System.Drawing.Pens.Gainsboro; } }
        public static Pen GhostWhite { get { return System.Drawing.Pens.GhostWhite; } }
        public static Pen Gold { get { return System.Drawing.Pens.Gold; } }
        public static Pen Goldenrod { get { return System.Drawing.Pens.Goldenrod; } }
        public static Pen Gray { get { return System.Drawing.Pens.Gray; } }
        public static Pen Green { get { return System.Drawing.Pens.Green; } }
        public static Pen GreenYellow { get { return System.Drawing.Pens.GreenYellow; } }
        public static Pen Honeydew { get { return System.Drawing.Pens.Honeydew; } }
        public static Pen HotPink { get { return System.Drawing.Pens.HotPink; } }
        public static Pen IndianRed { get { return System.Drawing.Pens.IndianRed; } }
        public static Pen Indigo { get { return System.Drawing.Pens.Indigo; } }
        public static Pen Ivory { get { return System.Drawing.Pens.Ivory; } }
        public static Pen Khaki { get { return System.Drawing.Pens.Khaki; } }
        public static Pen Lavender { get { return System.Drawing.Pens.Lavender; } }
        public static Pen LavenderBlush { get { return System.Drawing.Pens.LavenderBlush; } }
        public static Pen LawnGreen { get { return System.Drawing.Pens.LawnGreen; } }
        public static Pen LemonChiffon { get { return System.Drawing.Pens.LemonChiffon; } }
        public static Pen LightBlue { get { return System.Drawing.Pens.LightBlue; } }
        public static Pen LightCoral { get { return System.Drawing.Pens.LightCoral; } }
        public static Pen LightCyan { get { return System.Drawing.Pens.LightCyan; } }
        public static Pen LightGoldenrodYellow { get { return System.Drawing.Pens.LightGoldenrodYellow; } }
        public static Pen LightGreen { get { return System.Drawing.Pens.LightGreen; } }
        public static Pen LightGray { get { return System.Drawing.Pens.LightGray; } }
        public static Pen LightPink { get { return System.Drawing.Pens.LightPink; } }
        public static Pen LightSalmon { get { return System.Drawing.Pens.LightSalmon; } }
        public static Pen LightSeaGreen { get { return System.Drawing.Pens.LightSeaGreen; } }
        public static Pen LightSkyBlue { get { return System.Drawing.Pens.LightSkyBlue; } }
        public static Pen LightSlateGray { get { return System.Drawing.Pens.LightSlateGray; } }
        public static Pen LightSteelBlue { get { return System.Drawing.Pens.LightSteelBlue; } }
        public static Pen LightYellow { get { return System.Drawing.Pens.LightYellow; } }
        public static Pen Lime { get { return System.Drawing.Pens.Lime; } }
        public static Pen LimeGreen { get { return System.Drawing.Pens.LimeGreen; } }
        public static Pen Linen { get { return System.Drawing.Pens.Linen; } }
        public static Pen Magenta { get { return System.Drawing.Pens.Magenta; } }
        public static Pen Maroon { get { return System.Drawing.Pens.Maroon; } }
        public static Pen MediumAquamarine { get { return System.Drawing.Pens.MediumAquamarine; } }
        public static Pen MediumBlue { get { return System.Drawing.Pens.MediumBlue; } }
        public static Pen MediumOrchid { get { return System.Drawing.Pens.MediumOrchid; } }
        public static Pen MediumPurple { get { return System.Drawing.Pens.MediumPurple; } }
        public static Pen MediumSeaGreen { get { return System.Drawing.Pens.MediumSeaGreen; } }
        public static Pen MediumSlateBlue { get { return System.Drawing.Pens.MediumSlateBlue; } }
        public static Pen MediumSpringGreen { get { return System.Drawing.Pens.MediumSpringGreen; } }
        public static Pen MediumTurquoise { get { return System.Drawing.Pens.MediumTurquoise; } }
        public static Pen MediumVioletRed { get { return System.Drawing.Pens.MediumVioletRed; } }
        public static Pen MidnightBlue { get { return System.Drawing.Pens.MidnightBlue; } }
        public static Pen MintCream { get { return System.Drawing.Pens.MintCream; } }
        public static Pen MistyRose { get { return System.Drawing.Pens.MistyRose; } }
        public static Pen Moccasin { get { return System.Drawing.Pens.Moccasin; } }
        public static Pen NavajoWhite { get { return System.Drawing.Pens.NavajoWhite; } }
        public static Pen Navy { get { return System.Drawing.Pens.Navy; } }
        public static Pen OldLace { get { return System.Drawing.Pens.OldLace; } }
        public static Pen Olive { get { return System.Drawing.Pens.Olive; } }
        public static Pen OliveDrab { get { return System.Drawing.Pens.OliveDrab; } }
        public static Pen Orange { get { return System.Drawing.Pens.Orange; } }
        public static Pen OrangeRed { get { return System.Drawing.Pens.OrangeRed; } }
        public static Pen Orchid { get { return System.Drawing.Pens.Orchid; } }
        public static Pen PaleGoldenrod { get { return System.Drawing.Pens.PaleGoldenrod; } }
        public static Pen PaleGreen { get { return System.Drawing.Pens.PaleGreen; } }
        public static Pen PaleTurquoise { get { return System.Drawing.Pens.PaleTurquoise; } }
        public static Pen PaleVioletRed { get { return System.Drawing.Pens.PaleVioletRed; } }
        public static Pen PapayaWhip { get { return System.Drawing.Pens.PapayaWhip; } }
        public static Pen PeachPuff { get { return System.Drawing.Pens.PeachPuff; } }
        public static Pen Peru { get { return System.Drawing.Pens.Peru; } }
        public static Pen Pink { get { return System.Drawing.Pens.Pink; } }
        public static Pen Plum { get { return System.Drawing.Pens.Plum; } }
        public static Pen PowderBlue { get { return System.Drawing.Pens.PowderBlue; } }
        public static Pen Purple { get { return System.Drawing.Pens.Purple; } }
        public static Pen Red { get { return System.Drawing.Pens.Red; } }
        public static Pen RosyBrown { get { return System.Drawing.Pens.RosyBrown; } }
        public static Pen RoyalBlue { get { return System.Drawing.Pens.RoyalBlue; } }
        public static Pen SaddleBrown { get { return System.Drawing.Pens.SaddleBrown; } }
        public static Pen Salmon { get { return System.Drawing.Pens.Salmon; } }
        public static Pen SandyBrown { get { return System.Drawing.Pens.SandyBrown; } }
        public static Pen SeaGreen { get { return System.Drawing.Pens.SeaGreen; } }
        public static Pen SeaShell { get { return System.Drawing.Pens.SeaShell; } }
        public static Pen Sienna { get { return System.Drawing.Pens.Sienna; } }
        public static Pen Silver { get { return System.Drawing.Pens.Silver; } }
        public static Pen SkyBlue { get { return System.Drawing.Pens.SkyBlue; } }
        public static Pen SlateBlue { get { return System.Drawing.Pens.SlateBlue; } }
        public static Pen SlateGray { get { return System.Drawing.Pens.SlateGray; } }
        public static Pen Snow { get { return System.Drawing.Pens.Snow; } }
        public static Pen SpringGreen { get { return System.Drawing.Pens.SpringGreen; } }
        public static Pen SteelBlue { get { return System.Drawing.Pens.SteelBlue; } }
        public static Pen Tan { get { return System.Drawing.Pens.Tan; } }
        public static Pen Teal { get { return System.Drawing.Pens.Teal; } }
        public static Pen Thistle { get { return System.Drawing.Pens.Thistle; } }
        public static Pen Tomato { get { return System.Drawing.Pens.Tomato; } }
        public static Pen Turquoise { get { return System.Drawing.Pens.Turquoise; } }
        public static Pen Violet { get { return System.Drawing.Pens.Violet; } }
        public static Pen Wheat { get { return System.Drawing.Pens.Wheat; } }
        public static Pen White { get { return System.Drawing.Pens.White; } }
        public static Pen WhiteSmoke { get { return System.Drawing.Pens.WhiteSmoke; } }
        public static Pen Yellow { get { return System.Drawing.Pens.Yellow; } }
        public static Pen YellowGreen { get { return System.Drawing.Pens.YellowGreen; } }
        private Pens(){}
    }
}